include:
  - path: sophia-message-broker/docker-compose.yml
  - path: sophia-ai-service/docker-compose.yml
  - path: sophia-medication-service/docker-compose.yml
  - path: sophia-notification-service/docker-compose.yml
  - path: sophia-pharmacy-service/docker-compose.yml
  - path: sophia-frontend/docker-compose.yml
