events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream frontend_service   { server sophia-frontend:3000; }
    upstream pharmacy_service   { server pharmacy-service:8080; }
    upstream medication_service { server sophia-medication-service:3000; }

    proxy_set_header Host              $host;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    server {
        listen 80;
        server_name sophia.todpig.com.br;

        location /.well-known/acme-challenge/ { root /var/www/certbot; }
        location / { return 301 https://$host$request_uri; }
    }

    # HTTPS
    server {
        listen 443 ssl;
        server_name sophia.todpig.com.br;

        ssl_certificate     /etc/letsencrypt/live/sophia.todpig.com.br/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/sophia.todpig.com.br/privkey.pem;

        location /api/auth/               { proxy_pass http://pharmacy_service/auth/; }
        location /api/pharmacy/           { proxy_pass http://pharmacy_service/pharmacy/; }
        location /api/invites/            { proxy_pass http://pharmacy_service/invites/; }
        location /api/medications         { proxy_pass http://medication_service/medications; }
        location /api/medication-batches  { proxy_pass http://medication_service/medication-batches; }

        location / { proxy_pass http://frontend_service; }
    }
}
